config/routes.rb
Rails.application.routes.draw do
  root to: 'jerseys#index'
  resources :jerseys do
    resources :reviews
  end

  resources :jerseys do
    resources :bookings
  end

  resources :jerseys do
    resources :jersey_tags, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :jersey
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/jersey.rb
class Jersey < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :jersey_tags
  has_many :tags, through: :jersey_tags
  has_one_attached :photo

  validates :name, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :description, presence: true

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/jersey_tag.rb
class JerseyTag < ApplicationRecord
  belongs_to :jersey
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :jersey
  validates :content, length: { minimum: 20 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :jersey_tags
  has_many :tags, through: :jersey_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :make_booking, only: [:show, :edit, :update, :destroy]

  def new
    @jersey = Jersey.find(params[:jersey_id])
    @booking = Booking.new
  end

  def create
    @jersey = Jersey.find(params[:jersey_id])
    @booking = Booking.new(booking_params)
    @booking.jersey = @jersey
    
    if @booking.save
      redirect_to jersey_booking_path(@jersey, @booking)
    else
      render new
    end
  end

  def index
    @bookings = Booking.all
  end

  def show
    @jersey = @booking.jersey
  end

  def edit
    @jersey = Jersey.find(params[:jersey_id])
  end

  def update
    @jersey = Jersey.find(params[:jersey_id])
    if @booking.update(booking_params)
    redirect_to jersey_booking_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    flash[:alert] = "Your current booking was cancelled"
    redirect_to root_path
  end

  private

  def make_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/jersey_tags_controller.rb
class JerseyTagsController < ApplicationController
  def new
    @jersey_tag = JerseyTag.new
    @jersey = Jersey.find(params[:jersey_id])
  end

  def create
    @jersey = Jersey.find(params[:jersey_id])
    tag_ids = params[:jersey_tag][:tag_id]

    tag_ids.each do |tag_id|
      @tag = Tag.find(tag_id)
      @jersey_tag = JerseyTag.new(jersey: @jersey, tag: @tag)
      @jersey_tag.save
    end
    redirect_to jersey_path(@jersey)
  end
end

app/controllers/jerseys_controller.rb
class JerseysController < ApplicationController
  before_action :make_jersey, only: [:show, :edit, :update, :destroy]

  def index
    @jerseys = Jersey.all
  end

  def show
    @review = Review.new
  end

  def new
    @jersey = Jersey.new
  end

  def create
    @jersey = Jersey.new(jersey_params)
    if @jersey.save
      redirect_to jersey_path(@jersey)
    else
      render :new
    end
  end

  def edit 
  end

  def update 
    if @jersey.update(jersey_params)
      redirect_to jersey_path(@jersey) and return
    else
      render :edit
    end
  end

  def destroy
    @jersey.destroy
    flash[:alert] = 'You have successfully deleted your Jersey.'
    redirect_to jerseys_path
  end

  private

  def make_jersey
    @jersey = Jersey.find(params[:id])
    # authorize @jersey
  end

  def jersey_params
    params.require(:jersey).permit(:name, :price, :size, :description, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @jersey = Jersey.find(params[:jersey_id])
    @review = Review.new(review_params)
    @review.jersey = @jersey
    if @review.save
        redirect_to jersey_path(@jersey, anchor: "review-#{@review.id}")
    else
      flash[:alert] = "Something went wrong."
      :new
    end
  end
    
  private
    
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/jersey_tags_helper.rb
module JerseyTagsHelper
end

app/helpers/jerseys_helper.rb
module JerseysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookings/_form.html.erb
<div class="container" id='jersey-booking-dates' data-unavailable="<%= @jersey.unavailable_dates.to_json %>">
    <%= simple_form_for [@jersey, @booking] do |t| %>
      <%= t.input :start_date, as: :string, required: :true, input_html: { id: "booking_start_date" } %>
      <%= t.input :end_date, as: :string, required: :true, input_html: { id: "booking_end_date" } %>
      <%= t.submit "Confirm Your Booking", class: "btn btn-outline-success btn-sm" %>
    <% end %>
  <%= link_to "Back to Store", jerseys_path, class: "btn btn-outline-warning btn-sm" %>
</div>

app/views/bookings/new.html.erb
<div class="container" >
  <div>
    <h1> Perfect choice! <%=  @jersey.name %> </h1>
    <%= render 'form', jersey: @jersey %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <p>From: <%= @booking.start_date.strftime('%m/%d/%Y') %></p>
  <p>To: <%= @booking.end_date.strftime('%m/%d/%Y') %></p>
  <%= link_to "Continue shopping", jerseys_path, class: "btn btn-sm btn-primary mr-2" %> <%= link_to "Back to Store", jerseys_path, class: "btn btn-outline-warning btn-sm" %>
</div>

app/views/jersey_tags/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Add your tag for <%= @jersey.name %> amazing jersey!</h1>
       <%= simple_form_for [@jersey, @jersey_tag] do |c| %>
         <%= c.association :tag, input_html: { multiple: true, class: "multiple-select" }, include_hidden: false %>
         <%= c.submit "Add a Tag", class: "btn btn-sm btn-success" %>
        <% end %>
    </div>
  </div>
</div>

app/views/jerseys/_form.html.erb
<%= simple_form_for jersey do |c| %>
  <%= c.input :name %>
  <%= c.input :size %>
  <%= c.input :price %>
  <%= c.input :photo, as: :file %>
  <%= c.input :description %>
  <%= c.submit "#{jersey.id ? "Edit" : "Add" } Jersey", class: "btn btn-success" %>
<% end %>

app/views/jerseys/edit.html.erb
<div class="col-6 mt-5 offset-3">
  <%= render 'form', jersey: @jersey %>
</div>

app/views/jerseys/index.html.erb
<main>
  <section>
    <audio src="https://www.bensound.com/bensound-music/bensound-moose.mp3"></audio>
    <button id="btn-music"><i class="fas fa-volume-up"></i></button>
    <div class="panels">
    <div class="panel panel1">
      <p>Hey</p>
      <p>Let's</p>
      <p>Play</p>
    </div>
    <div class="panel panel2">
      <p>Give</p>
      <p>Take</p>
      <p>Play</p>
    </div>
    <div class="panel panel3">
      <p>Experience</p>
      <p>It</p>
      <p>Today</p>
    </div>
    <div class="panel panel4">
      <p>Give</p>
      <p>All</p>
      <p>You can</p>
    </div>
    <div class="panel panel5">
      <p>Life</p>
      <p>In</p>
      <p>Motion</p>
    </div>
  </div>
  </section>
</main>

<div class="container">
  <div class="mt-5">
    <h1>Throwback! Ranking the top jerseys in NBA history</h1>
    <h2>If you want to sell your vintage jersey, click the button!<%= link_to 'Add New Jersey', new_jersey_path, class: 'ml-2 btn btn-success' %></h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @jerseys.each do |jersey| %>
      <div class="card col-lg-3 m-4">
        <% jersey.photo.attached? ? @image = "//res.cloudinary.com/apak/image/upload/#{jersey.photo.key}": @image = jersey.image_scr %>
        <img class="card-img-top" src="<%= @image %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= jersey.name %></h5>
          <p class="card-text"><%= jersey.description %></p>
          <%= link_to "Show Details", jersey_path(jersey) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/jerseys/new.html.erb
<div class="col-6 mt-5 offset-3">
    <%= render 'form', jersey: @jersey %>
</div>

app/views/jerseys/show.html.erb
<div class="container">
 <div class="row mt-3">
   <div class="banner col-lg-6" style="background-image: url('<%= cl_image_path @jersey.photo.key%>');">
  </div>
  <div class="content col-lg-6">
    <h1><%= @jersey.name %></h1>
    <h2>Price: <strong><%= @jersey.price %></strong> AUD | Size: <strong><%= @jersey.size %></strong></h2>
    <h5><%= @jersey.description %></h5>
    <%= link_to "Buy It", new_jersey_booking_path(@jersey), class: "btn btn-lg btn-info" %>
    <%= link_to "Delete Your Jersey", @jersey, method: :delete, remote: true,  class: "btn btn-sm btn-danger" %>
    <%= link_to "Edit Your Jersey", edit_jersey_path(@jersey), class: "btn btn-sm btn-success" %>
    <%= link_to "Back to Store", jerseys_path, class: "btn btn-warning btn-sm" %>
  </div>
 </div>
</div>

<div class="container">
  <div class="row mt-4">
    <div class="tag-category">
      <% @jersey.tags.each do |tag| %>
      <span class="badge badge-warning mr-1"><%= tag.name %></span>
      <% end %>
      <%= link_to "Add a Tag",  new_jersey_jersey_tag_path(@jersey), class: "btn btn-success btn-sm" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="mt-5" id="reviews">  
    <h2><%= pluralize @jersey.reviews.size, "review" %></h2>
    <% if @jersey.reviews.blank? %>
      Be the first to leave a review for <%= @jersey.name %>
    <% else %>
      <% @jersey.reviews.each do |review| %>
        <p id="review-<%= review.id %>"><%= review.content %> </p>
        Rating: <%= review.rating.times do%>
        <i class="fas fa-star"></i>
        <%end%>
      <% end %>
    <% end %>
  </div>
</div>
     
<div class="container">
  <%= simple_form_for([ @jersey, @review ], remote: true) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
    <%= f.submit "Send your review", class: "btn btn-sm btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>